wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1671352123.443752
    t:
      1:
      - 1
      - 5
      - 11
      - 31
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 31
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.13
      5: 0.13.7
      6: 4.24.0
      8:
      - 1
      - 3
      - 5
